server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    #让 gateway 通过 nacos 实现自动路由转发
    gateway:
      discovery:
        locator:
          # 自动根据 URL 规则实现路由转发
          enabled: false
      routes:
        - id: service_a_route
          # lb 开头代表基于 gateway 的负载均衡策略选择实例
          uri: lb://service_a
          predicates:
            - Path=/a/**
            #After生效时间谓词，2020年10月15日后该路由才能在网关对外暴露
            - After=2020-10-05T00:00:00.000+08:00[Asia/Shanghai]
          filters:
            #忽略掉第一层前缀进行转发
            - StripPrefix=1
            #为响应头附加X-Response=Blue
            - AddResponseHeader=X-Response,Blue
        - id: service_b_route
          uri: lb://service-b
          predicates:
            - Path=/b/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"