server:
  port: 8005

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

# openfeign 配置
feign:
  compression:
    request:
      # 开启请求数据的压缩功能
      enabled: true
      # 压缩支持的MIME类型
      mime-types:
        - text/xml
        - application/xml
        - application/json
      # 数据压缩下限 表示传输数据大于 1024 才会进行数据压缩
      min-request-size: 1024
    response:
      enabled: true
  # 启用 OkHttp
  okhttp:
    enabled: true

