server:
  port: 8008

spring:
  application:
    name: sentinel-sample
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:9100
      eager: true # 取消控制台懒加载
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos

management:
  endpoints:
    web:
      exposure:
        - "*"