server:
  port: 8009

spring:
  application:
    name: a-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  sleuth:
    # 采样器
    sampler:
      probability: 1.0 #采样率，采样率是采集Trace的比率，默认0.1
      rate: 10000 #每秒数据采集量，最多n条/秒Trace
  zipkin:
    # 设置zipkin服务端地址
    base-url: http://localhost:9411

logging:
  level:
    root: debug #为演示需要，开启debug级别日志
