server:
  port: 9002

# seata配置
seata:
  # 开启 seata 分布式事务
  enabled: true
  # 事务服务分组名,与 naocs 一致
  tx-service-group: my_test_tx_group
  # 是否启用数据源代理
  enable-auto-data-source-proxy: true
  # 事务服务配置
  service:
    vgroup-mapping:
      # 事务分组对应集群名称
      my_test_tx_group: default
    grouplist:
      # Seata-Server 服务的 IP 地址与端口
      default: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false
  # Nacos 配置中心信息
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      cluster: default
  # Nacos 注册中心信息
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username: nacos
      password: nacos
      cluster: default

# 应用配置
spring:
  application:
    name: rm-points
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3312/rm-points
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
  jpa:
    show-sql: true

logging:
  level:
    io:
      seata: debug
